print("###############################")
print("# minha calculadora de fisica #")
print("###############################\n\n")
print("vamos começar calculando meu IMC")
peso = float(input("qual é meu peso?\n"))
altura = float(input("qual é a minha altura"))
print("meu IMC é",peso/altura**2)
